%  Example for the ETH Beamer template
%  Copyright 2014 by
%  Dr. Antonios Garas,
%  Chair of Systems Design, ETH Zurich
%  Weinbergstrasse 56/58 CH-8092 Zurich
%
\pdfminorversion=4
\documentclass[
%aspectratio=169,
first,
%handout,
%compress,
%Helv,
ETH3, %ETH1,
navigation
]{ETHbeamerclass}

% Options for beamer:
%
% compress: navigation bar becomes smaller
% t       : place contents of frames on top (alternative: b,c)
% handout : handoutversion
% notes   : show notes
% notes=onlyslideswithnotes
%
\setbeamertemplate{note page}{\ \\[.3cm]
\textbf{\color{colorSG}Notes:}\\%[0.1cm]
{\footnotesize %\tiny
\insertnote}}

\setbeameroption{hide notes}
%\setbeameroption{show notes}

\setbeamertemplate{navigation symbols}{} % suppresses all navigation symbols:
% \setbeamertemplate{navigation symbols}[horizontal] % Organizes the navigation symbols horizontally.
% \setbeamertemplate{navigation symbols}[vertical] % Organizes the navigation symbols vertically.
% \setbeamertemplate{navigation symbols}[only frame symbol] % Shows only the navigational symbol for navigating frames.

\usepackage{amsmath, amssymb}
\usepackage{pifont}
\usepackage{multimedia}

%--------------------------------------------------------------------------------------------------------
%--- Some custom definitions...

\definecolor{cbf}{RGB}{199,100,95}%{163,15,0}
\newcommand{\cbf}{\color{cbf}}

\newcommand{\mean}[1]{\left\langle #1 \right\rangle}
\newcommand{\abs}[1]{\left| #1 \right|}

%--------------------------------------------------------------------------------------------------------
%--- Inputs for the title page...

\title{Selektionsindex - Zuchtwert - Verwandtschaft}
\newcommand{\shorttitle}{}

\author{Peter von Rohr}
\date{\today}
\institute{Qualitas AG}

\newcommand{\collaborators}{}
\newcommand{\event}{Folien ZL I+II}
\newcommand{\place}{LFW C11}

\newcommand{\Prob}{\mathrm{Pr}}
\newcommand{\sign}{\mathrm{sign}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\N}{\mathbb{N}}
\newcommand{\nbin}[1]{\mathrm{nb}_\mathrm{in}(#1)}
\newcommand{\nbout}[1]{\mathrm{nb}_\mathrm{out}(#1)}
\newcommand{\one}{\mathbb{\bf 1}}

\newcommand{\sref}[1]{SLIDE \ref{#1}}

%--------------------------------------------------------------------------------------------------------
%--- Here begins the presentation...

\begin{document}
\SweaveOpts{concordance=TRUE}

\frame{
\maketitle
}
\note{}


\section{R\"uckblick Zuchtwert}

\frame{
  \frametitle{Zusammenfassung Zuchtwert aus Quantitativer Genetik}
  \begin{block}{Modell der ph\"anotypischen Beobachtung}
    \begin{itemize}
    \item Zerlegung der gemessenen ph\"anotypischen Wertes (Beobachung) ($p$)
    \item Komponenten sind \emph{genotypischer Wert} ($g$) und \emph{Umweltabweichung} ($e$)
    \item $p = g + e$
    \item Erwartungswerte: Im Schnitt \"uber eine Population werden die Umweltabweichungen $e$ als Null angenommen
    \item $E\left[ e\right] = 0$ und somit $E\left[p \right] = E\left[ g\right]$
    \end{itemize}
  \end{block}
}
\note{}


\frame{
  \frametitle{Genotypischer Wert (GW)}
  \begin{itemize}
  \item GW erfasst den genetisch bedingten Teil des ph\"anotypischen Wertes
  \item Annahme: 1 Genort, 2 Allele, Population im Hardy-Weinberg Gleichgewicht
  \item F\"ur bestimmten Genotypen $G_iG_j$ ist der genotypische Wert $V_{ij}$
    definiert als der mittlere Wert aller Individuen in der gleichen Umwelt mit
    Genotyp $G_iG_j$
  \end{itemize}
}
\note{}


\frame{
  \frametitle{Genotypischer Wert (GW) II}
  \begin{itemize}
  \item Nullpunkt der Skala in Mitte zwischen Homozygoten $G_1G_1$ und $G_2G_2$
  \item Wahl des Nullpunkts beliebig, so am einfachsten
  \end{itemize}
  \includegraphics[width=\textwidth]{figure/w3/GenotypischerWert}
}
\note{}


\frame{
  \frametitle{Zusammenfassung Genotypische Werte}
  \begin{center}
   {\renewcommand{\arraystretch}{1.7}
   \renewcommand{\tabcolsep}{0.2cm}
   \begin{tabular}{|l|c|}
  \hline
  Genotyp  &  genotypischer Wert\\
  \hline
  $G_1G_1$  &  $V_{11} = a$\\
  \hline
  $G_1G_2$  &  $V_{12} = d$\\
  \hline
  $G_2G_2$  &  $V_{22} = -a$\\
  \hline
  \end{tabular}}
  \end{center}
}
\note{}


\frame{
  \frametitle{Populationsmittel - Erwartungswert}
  \begin{itemize}
  \item Populationsmittel $\mu$ als Erwartungswert $E\left[V\right]$ der genotypischen Werte
  \item Allgemeine Definition des Erwartungswertes einer diskreten Zufallsvariablen $X$
  \end{itemize}

  $$E\left[X\right] = \sum_{x_i\in \mathcal{X}} x_i* f(x_i)$$

  \vspace*{1ex}
  \begin{tabular}{p{1cm}p{1cm}p{6cm}}
  wobei & $\mathcal{X}$: &  Menge aller m\"oglichen $x$-Werte\\
        & $f(x_i)$         &  Wahrscheinlichkeit dass $x$ den Wert $x_i$ annimmt
  \end{tabular}

}
\note{}


\frame{
  \frametitle{Erwartungswert der genotypischen Werte}

  \noindent F\"ur unser Beispiel mit den genotypischen Werten

  \begin{itemize}
  \item Menge an m\"oglichen Werten $\mathcal{X} = \{V_{11}, V_{12}, V_{22} \}$
  \item Frequenzen der genotypischen Werte entspricht Frequenz der Genotypen
  \item Mit Allelfrequenzen $f(G_1) = p$ und $f(G_2) = q = 1-p$ folgen die Genotypfrequenzen
  \end{itemize}

  \begin{tabular}{|l|c|}
  \hline
  Genotyp  &  Frequenzen\\
  \hline
  $G_1G_1$  &  $p*p = p^2$\\
  \hline
  $G_1G_2$  &  $p*q+q*p = 2pq$\\
  \hline
  $G_2G_2$  &  $q*q = q^2$\\
  \hline
  \end{tabular}


}
\note{}


\frame{
  \frametitle{Populationsmittel als Erwartungswert}
  \begin{itemize}
  \item Einsetzen der genotypischen Werte und der Genotypfrequenzen in Definition des Erwartungswertes
  \end{itemize}

  \begin{eqnarray}
  \mu & = & E\left[V\right]\\
      & = & f(G_1G_1)*V_{11} + f(G_1G_2) * V_{12} + f(G_2G_2) * V_{22} \nonumber
  \end{eqnarray}
}
\note{}


\frame{
  \frametitle{Populationsmittel unter Hardy-Weinberg}
  Aufgrund der Genotypfrequenzen folgt

  \begin{eqnarray}
    \mu &=& p^2 * a + 2pq*d - q^2*a\\
        &=& (p^2 - q^2)a + 2pqd \nonumber \\
        &=& (p+q)(p - q)a + 2pqd \nonumber \\
        &=& (p - q)a + 2pqd \nonumber
  \end{eqnarray}

  $\rightarrow$ Das Populationsmittel ist somit abh\"angig von den Allelfrequenzen und somit von der Selektion
}
\note{}


\frame{
  \frametitle{Zuchtwert}
  \begin{itemize}
  \item Bei Zucht interessiert, welche genetischen Anlagen von Eltern an Nachkommen weitergegeben werden
  \item Eltern geben nicht Genotypen sondern zuf\"allige Stichprobe der Allele an Nachkommen weiter
  \item $\rightarrow$ Frage, welche Leistung kann von Nachkommen eines bestimmten Elterngenotyps erwartet werden
  \item Zuchtwert wird verwendet als Mass f\"ur die mittlere Leistung von Nachkommen eines bestimmten Tieres im Vergleich zum Populationsmittel
  \item Definition \textbf{Zuchtwert}: entspricht der doppelten Abweichung des erwarteten Mittelwertes von Nachkommen vom Populationsmittel
  \end{itemize}
}
\note{}


\frame{
  \frametitle{Herleitung des Zuchtwertes f\"ur Genotyp $G_1G_1$}
  \begin{itemize}
  \item Frequenz der Nachkommen
    \begin{tabular}{|c|c|c|}
      \hline
                   & \multicolumn{2}{|c|}{Vater} \\
      \hline
                   & $f(G_1) = p$       &  $f(G_2) = q$   \\
      \hline
      Mutter       &                    &                 \\
      \hline
      $f(G_1) = 1$ &  $f(G_1G_1) = p$   &  $f(G_1G_2) = q$\\
      \hline
    \end{tabular}
  \item Erwarteter mittlerer genotypischer Wert $\mu_{11}$ der Nachkommen einer Mutter mit Genotyp $G_1G_1$
  $$\mu_{11} = pa + qd$$
  \item Gem\"ass Definition, entspricht der Zuchtwert $ZW_{11}$ der Mutter mit Genotyp $G_1G_1$ der doppelten
    Abweichung des mittleren genotypischen Wertes $\mu_{11}$ der Nachkommen vom Populationsmittel $\mu$
  \end{itemize}
}
\note{}


\frame{
  \frametitle{Zuchtwert $ZW_{11}$ f\"ur Genotyp $G_1G_1$}
  \begin{itemize}
  \item Doppelte Abweichung der Nachkommen vom Populationsmittel
  \item Einsetzen der berechneten Gr\"ossen f\"ur $\mu_{11}$ und $\mu$
  \end{itemize}
  \begin{eqnarray}
  ZW_{11} &=& 2*(\mu_{11} - \mu) \\
          &=& 2\left(pa + qd - \left[(p - q)a + 2pqd \right] \right) \nonumber\\
          &=& 2\left(pa + qd - (p - q)a - 2pqd \right) \nonumber\\
          &=& 2\left(qd + qa - 2pqd\right) \nonumber \\
          &=& 2\left(qa + qd(1 - 2p)\right) \nonumber \\
          &=& 2q\left(a + d(1 - 2p)\right) \nonumber \\
          &=& 2q\left(a + (q-p)d\right) \nonumber
  \end{eqnarray}

  \vspace*{1ex}\noindent
  Falls Locus $G$ rein additiv $\rightarrow d = 0$, somit ist $ZW_{11} = 2qa$
}
\note{}


\frame{
  \frametitle{Zuchtwert $ZW_{22}$ f\"ur Genotyp $G_2G_2$}
  \begin{itemize}
  \item Frequenz der Nachkommen

    \begin{tabular}{|c|c|c|}
      \hline
                   & \multicolumn{2}{|c|}{Vater} \\
      \hline
                   & $f(G_1) = p$       &  $f(G_2) = q$   \\
      \hline
      Mutter       &                    &                 \\
      \hline
      $f(G_2) = 1$ &                    &                 \\
      \hline
    \end{tabular}

  \vspace*{1ex}
  \item Erwarteter mittlerer genotypischer Wert $\mu_{22} = $

  \vspace*{3ex}
  \item Zuchtwert $ZW_{22} = $
  \end{itemize}
}
\note{}


\frame{
  \frametitle{Zuchtwert $ZW_{12}$ f\"ur Genotyp $G_1G_2$}
  \begin{itemize}
  \item Frequenz der Nachkommen

    \begin{tabular}{|c|c|c|}
      \hline
                     & \multicolumn{2}{|c|}{Vater} \\
      \hline
                     & $f(G_1) = p$       &  $f(G_2) = q$   \\
      \hline
      Mutter         &                    &                 \\
      \hline
      $f(G_1) = 0.5$ &                    &                 \\
      \hline
      $f(G_2) = 0.5$ &                    &                 \\
      \hline
    \end{tabular}

  \vspace*{1ex}
  \item Erwarteter mittlerer genotypischer Wert $\mu_{12} = $

  \vspace*{3ex}
  \item Zuchtwert $ZW_{12} = $
  \end{itemize}
}
\note{}


\frame{
  \frametitle{Allelsubstitution}
  \begin{itemize}
  \item Bei allen Zuchtwerten kommt der Term $a + (q-p)d$ vor. Dieser wird mit $\alpha$ bezeichnet
  \item Zuchtwerte als Funktion von $\alpha$
  \end{itemize}

  \vspace*{1ex}
  \begin{center}
  \begin{tabular}{|c|c|}
  \hline
  Genotyp  &  Zuchtwert\\
  \hline
  $G_1G_1$  &  $2q\alpha$\\
  \hline
  $G_1G_2$  &  $(q-p)\alpha$\\
  \hline
  $G_2G_2$  &  $-2p\alpha$\\
  \hline
  \end{tabular}
  \end{center}

}
\note{}


\frame{
  \frametitle{Allelsubstitution II}
  \begin{itemize}
  \item Vergleicht man einen $G_2G_2$ Genotyp mit einem $G_1G_2$ Genotyp, dann wurde ein $G_2$-Allel durch ein $G_1$-Allel ersetzt
  \item Die Zuchtwerte \"andern sich von $ZW_{22}$ zu $ZW_{12}$
  \item \"Anderung der Zuchtwerte:
  \end{itemize}

  \begin{eqnarray}
    ZW_{12} - ZW_{22} & = & (q-p)\alpha - \left( -2p\alpha \right) \\
                      & = & (q-p)\alpha + 2p\alpha \nonumber \\
                      & = & (q-p+2p)\alpha \nonumber \\
                      & = & (q+p)\alpha \nonumber \\
                      & = & \alpha \nonumber
  \end{eqnarray}

}
\note{}


\frame{
  \frametitle{Allelsubstitution III}
  \begin{itemize}
  \item Analoger Vergleich zwischen Genotypen $G_1G_2$ und $G_1G_1$ f\"uhrt zu
  \end{itemize}

  \begin{eqnarray}
    ZW_{11} - ZW_{12} & = & 2q\alpha - (q-p)\alpha \\
                      & = & \left(2q - (q-p)\right)\alpha \nonumber\\
                      & = & \alpha \nonumber
  \end{eqnarray}
  \begin{itemize}
  \item Zuchtwerte sind von den Allelfrequenzen abh\"angig
  \item Differenzen zwischen Zuchtwerten sind additiv
  \end{itemize}
}
\note{}


\frame{
  \frametitle{Dominanzabweichung}
  \begin{itemize}
  \item Zuchtwert definiert als doppelte Abweichung des erwarteten mittleren Wertes der Nachkommen vom Populationsmittel
  \item Somit wird f\"ur einen bestimmten Genotypen $G_iG_j$ der genotypische Wert $V_{ij}$ vom Zuchtwert $ZW_{ij}$ abweichen.
  \item F\"ur die Genotypen $G_1G_1$, $G_1G_2$ und $G_2G_2$ sehen die Abweichungen wie folgt aus
  \end{itemize}

  \begin{eqnarray}
  V_{11} - ZW_{11} & = & a - 2q \alpha \\
                   & = & a - 2q \left[ a + (q-p)d \right] \nonumber \\
                   & = & a - 2qa -2q(q-p)d \nonumber \\
                   & = & a(1-2q) - 2q^2d + 2pqd \nonumber \\
                   & = & \left[(p - q)a + 2pqd\right] - 2q^2d \nonumber \\
                   & = & \mu + D_{11} \nonumber
  \end{eqnarray}
}
\note{}


\frame{
  \frametitle{Dominanzabweichung II}
  \begin{itemize}
  \item F\"ur Genotyp $G_1G_2$
  \end{itemize}

  \begin{eqnarray}
  V_{12} - ZW_{12} & = & d - (q-p)\alpha \\
                   & = & d - (q-p)\left[ a + (q-p)d \right] \nonumber \\
                   & = & \left[(p-q)a + 2pqd\right] + 2pqd \nonumber \\
                   & = & \mu + D_{12} \nonumber
  \end{eqnarray}

  \begin{itemize}
  \item F\"ur Genotyp $G_2G_2$
  \end{itemize}

  \begin{eqnarray}
  V_{22} - ZW_{22} & = & -a - (-2p\alpha) \\
                   & = & -a + 2p\left[ a + (q-p)d \right] \nonumber \\
                   & = & \left[(p-q)a + 2pqd\right] - 2p^2d \nonumber \\
                   & = & \mu + D_{22} \nonumber
  \end{eqnarray}
}
\note{}


\frame{
  \frametitle{Zusammenfassung Dominanzabweichung}
  {\renewcommand{\arraystretch}{1.7}
   \renewcommand{\tabcolsep}{0.2cm}
   \begin{tabular}{|c|c|c|c|}
   \hline
   Genotyp  &  genotypischer Wert  &  Zuchtwert     &  Dominanzabweichung\\
   $G_iG_j$ &  $V_{ij}$            &  $ZW_{ij}$     &  $D_{ij}$           \\
   \hline
   $G_1G_1$ &  $a$                 &  $2q\alpha$    &  $-2q^2d$          \\
   \hline
   $G_1G_2$ &  $d$                 &  $(q-p)\alpha$ & $2pqd$             \\
   \hline
   $G_2G_2$ &  $-a$                &  $-2p\alpha$   & $-2p^2d$           \\
   \hline
   \end{tabular}}

   \begin{itemize}
   \item Die genotypischen Werte k\"onnen mit folgendem Modell beschrieben werden
   \end{itemize}

   $$V_{ij} = \mu + ZW_{ij} + D_{ij}$$

}
\note{}


\frame{
  \frametitle{Varianzen}
  \begin{itemize}
  \item Populationsmittel der genotypischen Werte ($\mu = E(V)$) gibt Informationen zur Lage einer Population
  \item Varianz $\sigma_G^2 = Var\left[V\right]$ gibt an, wie gross Streuung um Populationsmittel
  \item Definition der Varianz f\"ur diskrete Zufallsvariable $X$
  \end{itemize}

  $$Var\left[X\right] = \sum_{x_i \in \mathcal{X}} (x_i - \mu_X)^2 * f(x_i)$$

  \vspace*{1ex}
  \begin{tabular}{p{1cm}p{1cm}p{6cm}}
  wobei & $\mathcal{X}$: &  Menge aller m\"oglichen $x$-Werte\\
        & $f(x_i)$       &  Wahrscheinlichkeit dass $x$ den Wert $x_i$ annimmt \\
        & $\mu_X $       &  Erwartungswert $E\left[X\right]$ von $X$
  \end{tabular}
}
\note{}


\frame{
  \frametitle{Varianzen der genotypischen Werte}
  Einsetzen der Frequenzen und der genotypischen Werte in die Definition der Varianz

  \begin{eqnarray}
  \sigma_G^2 = Var\left[V\right] &=&   (V_{11} - \mu)^2 * f(G_1G_1)           \\
                                 & & + (V_{12} - \mu)^2 * f(G_1G_2) \nonumber \\
                                 & & + (V_{22} - \mu)^2 * f(G_2G_2) \nonumber \\
                                 &=&   (a      - \mu)^2 * p^2       \nonumber \\
                                 & & + (d      - \mu)^2 * 2pq       \nonumber \\
                                 & & + (-a     - \mu)^2 * q^2       \nonumber
  \end{eqnarray}

  wobei $\mu = (p - q)a + 2pqd$ das Populationsmittel
}
\note{}


\frame{
  \frametitle{Herleitung der Varianz}
  Zur Herleitung der Varianz $\sigma_G^2$ verwenden wir, dass $V_{ij} = \mu + ZW_{ij} + D_{ij}$ und somit

    \begin{eqnarray}
  \sigma_G^2  &=&   (ZW_{11} + D_{11})^2 * p^2                \\
              & & + (ZW_{12} + D_{12})^2 * 2pq      \nonumber \\
              & & + (ZW_{22} + D_{22})^2 * q^2      \nonumber \\
              &=&   (2q\alpha    - 2q^2d)^2 * p^2   \nonumber \\
              & & + ((q-p)\alpha + 2pqd)^2 * 2pq    \nonumber \\
              & & + (-2p\alpha   - 2p^2d)^2 * q^2   \nonumber \\
              & & ...                               \nonumber \\
              &=& 2pq\alpha^2 + (2pqd)^2            \nonumber
  \end{eqnarray}

}
\note{}


\frame{
  \frametitle{Aufteilung der Varianz}
  \begin{itemize}
  \item Aufteilung von $\sigma_G^2 = 2pq\alpha^2 + (2pqd)^2$ in die zwei Terme
  \item Term $2pq\alpha^2$ heisst \textbf{genetisch additive Varianz} und wird mit $\sigma_A^2$ bezeichnet
  \item Term $(2pqd)^2$ heisst \textbf{Dominanzvarianz} und wird mit $\sigma_D^2$ bezeichnet.
  \item Somit ist $\sigma_G^2 = \sigma_A^2 + \sigma_D^2$
  \end{itemize}
}
\note{}


\section{Verwandtschaft}

\frame{
  \frametitle{Verwandtschaft}
  \begin{itemize}
  \item Bei k\"unstlicher Selektion sollen Tiere mit g\"unstigen Eigenschaften ausgew\"ahlt werden
  \item Ausgew\"ahlte Elterntiere sind in wichtigen Eigenschaften \"ahnlich
  \item Herkunft der \"Ahnlichkeit ist entscheidend
  \item Es wird unterschieden zwischen \textbf{zustandsgleich} (identical by state - IBS) und \textbf{herkunftsgleich} (identical by descent - IBD)
  \end{itemize}

}
\note{}


\frame{
  \frametitle{IBD vs. IBS}
  \includegraphics[width=\textwidth]{figure/w3/ibd_ibs}
}
\note{}


\frame{
  \frametitle{Definition Verwandtschaft}
  \begin{itemize}
  \item Zwei Tiere $x$ und $y$ sind verwandt, wenn die Wahrscheinlichkeit, dass sie an einem beliebigen Locus herkunftsgleiche Allele (IBD) aufweisen, $>0$ ist.
  \item \textbf{Verwandtschaftsgrad} $a_{xy}$ beschreibt die mittlere Wahrscheinlichkeit \"uber alle Loci, dass diese IBD sind
  \item Allgemeine Berechnung des Verwandtschaftsgrades $a_{xy}$ zwischen Tieren $x$ und $y$
  \end{itemize}

  $$a_{xy} = \sum_{Pfade} \left({1\over 2}\right)^{t_1+t_2}(1+F_Z)$$

  wobei $\sum_{Pfade}$ die Summe \"uber alle Pfade im Pedigree meint, $t_1$ und $t_2$ die Anzahl Generationen von $x$ und $y$ zum gemeinsamen Ahnen $Z$ und $F_Z$ den Inzuchtgrad von $Z$
}
\note{}


\frame{
  \frametitle{Inzucht}
  \begin{itemize}
  \item Tier $x$ ist ingez\"uchtet, falls seine Eltern $M_x$ und $V_x$ verwandt sind miteinander
  \item Inzucht beschreibt, ob in einem Tier $x$ an einem beliebigen Locus herkunftsgleiche Allele vorliegen
  \item Sind Allele IBD, dann m\"ussen sie Kopien vom gleichen Ahnenallel sein.
  \item Berechnung des Inzuchtgrades f\"ur das Tier $x$
  \end{itemize}

  $$F_x = {1\over 2}a_{M_x,V_x}
        = {1\over 2} \sum_{Pfade} \left({1\over 2}\right)^{t_1+t_2}(1+F_Z)
        = \sum_{Pfade} \left({1\over 2}\right)^{t_1+t_2+1}(1+F_Z)$$
}
\note{}


\frame{
  \frametitle{Matrixmethode}
  Zur Berechnung der Verwandtschaftsgrade und der Inzuchtgrade wurde folgende Methode entwickelt
  \begin{itemize}
  \item Tiere dem Alter nach von links nach rechts in einer symmetrischen Matrix anordnen
  \item Oberhalb jedes Tieres werden Eltern angef\"ugt
  \item Ausf\"ullen der Matrix getrennt nach Diagonalelementen und anderen
    \begin{enumerate}
    \item Diagonalelemente: $1+F_x$
    \item Off-Diagonal Elemente: $a_{xy} = {1\over 2}(a_{x,M_y} + a_{x,V_y})$
    \end{enumerate}
  \end{itemize}
}
\note{}


\frame{
  \frametitle{Beispielpedigree}
  \includegraphics[width=\textwidth]{figure/w3/MatMethPedigree}
}
\note{}


\end{document}
