\documentclass{article}

\begin{document}
\SweaveOpts{concordance=TRUE}

\title{Pr\"ufung Z\"uchtungslehre\\
       HS 2015}
\author{Peter von Rohr}
\maketitle

Drei der vier folgenden Themengebiete werden als Pr\"ufungsfragen verwendet.


\section*{Aufgabe 1: Verwandtschaft und Inzucht ()}


\clearpage
\pagebreak

\section*{Aufgabe 2: R ()}

\clearpage
\pagebreak

\section*{Aufgabe 3: Selektionsindex ()}

\clearpage
\pagebreak

\section*{Aufgabe 4: Ein-Lokus-Modell ()}


\end{document}
